project_id = "kbeeuzqdvpsyzyovinyp"

[functions.real-migration-to-storage]
verify_jwt = false

[functions.migrate-images-to-storage]
verify_jwt = false

[functions.upload-school-images]
verify_jwt = false

[functions.get-school-images]
verify_jwt = false

[functions.upload-school-image]
verify_jwt = false