-- Insert new culinary schools from the provided data
INSERT INTO public.schools (
    name, description, country, city, address, website, email, phone, type,
    founded, students_count, programs_count, rating, tuition_min, tuition_max,
    tuition_currency, specialties, accreditation, features, languages,
    coordinates_lat, coordinates_lng, is_active
) VALUES 
-- Escuela de Hostelería AIALA
('Escuela de Hostelería AIALA', 
 'Escuela de hostelería ubicada en Zarautz, Gipuzkoa, especializada en formación culinaria profesional.',
 'Spain', 'Zarautz', 'Av. de Navarra, 61, 20800 Zarautz, Gipuzkoa',
 'http://www.aiala.es/', 'cocina@aiala.es', '+34 943 13 46 00', 'Escuela',
 1980, 200, 5, 4.6, 3000, 8000, 'EUR',
 '["Cocina profesional", "Hostelería", "Servicio de mesa"]'::jsonb,
 '["Certificación oficial"]'::jsonb,
 '["Acceso para sillas de ruedas", "Aparcamiento adaptado"]'::jsonb,
 '["Español", "Euskera"]'::jsonb,
 43.2821268, -2.1506127, true),

-- CIFP Instituto Agrario ARKAUTE  
('CIFP Instituto Agrario ARKAUTE',
 'Centro de formación profesional especializado en sector agrario y alimentario en Vitoria-Gasteiz.',
 'Spain', 'Vitoria-Gasteiz', 'N-104, Km. 355, 01192 Vitoria-Gasteiz, Álava',
 'http://www.arkaute.net/', 'arkaute@arkaute.net', '+34 945 28 53 87', 'Centro de formación profesional',
 1985, 300, 8, 3.7, 2000, 6000, 'EUR',
 '["Industrias alimentarias", "Tecnología de alimentos", "Agricultura"]'::jsonb,
 '["FP oficial", "Certificación europea"]'::jsonb,
 '["Laboratorios especializados", "Granja experimental"]'::jsonb,
 '["Español", "Euskera"]'::jsonb,
 42.8541862, -2.6254403, true),

-- HAZI Fundazioa
('HAZI Fundazioa',
 'Fundación especializada en desarrollo rural y sostenibilidad alimentaria en el País Vasco.',
 'Spain', 'Arcaute', 'Granja Modelo, s/n, 01192 Arcaute, Álava',
 'https://hazi.eus/', 'lopd@hazi.eus', '+34 945 00 32 40', 'Fundación',
 1997, 150, 12, 4.3, 1500, 5000, 'EUR',
 '["Desarrollo rural", "Sostenibilidad", "Innovación alimentaria"]'::jsonb,
 '["Certificación ISO", "Reconocimiento europeo"]'::jsonb,
 '["Centro de investigación", "Granja modelo"]'::jsonb,
 '["Español", "Euskera"]'::jsonb,
 42.852403, -2.624251, true),

-- Kookin Donosti
('Kookin Donosti',
 'Escuela de cocina en San Sebastián especializada en experiencias gastronómicas vascas auténticas.',
 'Spain', 'Donostia-San Sebastian', 'C. Corta, 3 - Bajo, 20001 Donostia-San Sebastian, Gipuzkoa',
 'http://www.kookindonosti.com/', 'info@kookindonosti.com', '+34 680 66 04 88', 'Escuela de cocina',
 2015, 50, 4, 4.9, 80, 300, 'EUR',
 '["Cocina vasca", "Tours gastronómicos", "Talleres temáticos"]'::jsonb,
 '["Experiencia certificada"]'::jsonb,
 '["Clases prácticas", "Tours por mercados", "Cenas privadas"]'::jsonb,
 '["Español", "Euskera", "Inglés"]'::jsonb,
 43.3216996, -1.9746638, true),

-- Atelier Hermanas Loro
('Atelier Hermanas Loro',
 'Escuela de cocina dirigida por mujeres emprendedoras en Logroño, especializada en repostería y cocina creativa.',
 'Spain', 'Logroño', 'C/ Pilar Salarrullana, 13, 26002 Logroño, La Rioja',
 'https://atelierhermanasloro.com/', 'contacto@atelierhermanasloro.com', '+34 628 93 38 52', 'Escuela de cocina',
 2018, 30, 6, 4.8, 60, 200, 'EUR',
 '["Repostería", "Cocina creativa", "Talleres infantiles"]'::jsonb,
 '["Certificación artesanal"]'::jsonb,
 '["Propiedad femenina", "Clases personalizadas", "Acceso para sillas de ruedas"]'::jsonb,
 '["Español"]'::jsonb,
 42.4620586, -2.4477457, true),

-- Taller de cocina Umami
('Taller de cocina Umami',
 'Escuela de hostelería en Logroño especializada en talleres gastronómicos y técnicas culinarias avanzadas.',
 'Spain', 'Logroño', 'C. del Nte., 15, 26001 Logroño, La Rioja',
 'http://tallerdecocinaumami.com/', 'info@tallerdecocinaumami.com', '+34 645 67 98 87', 'Escuela de hostelería',
 2016, 40, 5, 4.8, 70, 250, 'EUR',
 '["Técnicas culinarias", "Cocina molecular", "Maridajes"]'::jsonb,
 '["Certificación profesional"]'::jsonb,
 '["Laboratorio gastronómico", "Acceso para sillas de ruedas"]'::jsonb,
 '["Español"]'::jsonb,
 42.4675521, -2.4491672, true),

-- Artisan Culinary School
('Artisan Culinary School',
 'Escuela culinaria boutique ubicada en la Costa Blanca, especializada en gastronomía mediterránea.',
 'Spain', 'Altea', 'Avinguda Rei en Jaume I, 03590 Altea, Alicante',
 'http://www.artisanculinaryschool.com/', 'info@artisanculinaryschool.com', '+34 689 68 99 96', 'Escuela de cocina',
 2010, 25, 8, 5.0, 150, 500, 'EUR',
 '["Gastronomía mediterránea", "Cocina artesanal", "Cursos intensivos"]'::jsonb,
 '["Certificación internacional"]'::jsonb,
 '["Escuela boutique", "Entorno mediterráneo", "Clases reducidas"]'::jsonb,
 '["Español", "Inglés"]'::jsonb,
 38.6018085, -0.0473511, true),

-- Escuela de Hostelería y Turismo Camino de Santiago
('Escuela de Hostelería y Turismo Camino de Santiago',
 'Centro de formación profesional en Santo Domingo de la Calzada, especializado en hostelería y turismo.',
 'Spain', 'Santo Domingo de la Calzada', 'C. Mayor, 83, 26250 Santo Domingo de la Calzada, La Rioja',
 'https://cipfpcaminodesantiago.larioja.edu.es/', 'hola@ehoja.com', '+34 941 34 29 20', 'Centro de formación profesional',
 1990, 180, 10, 4.6, 2500, 7000, 'EUR',
 '["Hostelería", "Turismo", "Gestión hotelera"]'::jsonb,
 '["FP oficial", "Título europeo"]'::jsonb,
 '["Hotel escuela", "Restaurante pedagógico", "Acceso para sillas de ruedas"]'::jsonb,
 '["Español"]'::jsonb,
 42.4408851, -2.9553222, true),

-- Escuela de Hostelería de Galdakao
('Escuela de Hostelería de Galdakao',
 'Centro de formación profesional en Galdakao, Bizkaia, reconocido por su excelencia en hostelería.',
 'Spain', 'Galdakao', 'Sixta Barrenetxea Kalea, 24, 48960 Galdakao, Bizkaia',
 'http://www.hosteleriagaldakao.com/', 'info@hosteleriagaldakao.com', '+34 944 56 04 58', 'Centro de formación profesional',
 1985, 400, 12, 4.8, 2000, 6500, 'EUR',
 '["Cocina profesional", "Servicio de restaurante", "Pastelería"]'::jsonb,
 '["FP oficial", "Certificación europea"]'::jsonb,
 '["Restaurante escuela", "LGTBI+ friendly", "Servicios adaptados"]'::jsonb,
 '["Español", "Euskera"]'::jsonb,
 43.2333214, -2.8568643, true),

-- Le Cordon Bleu Madrid
('Le Cordon Bleu Madrid',
 'Sede española de la prestigiosa institución francesa, líder mundial en artes culinarias y hostelería.',
 'Spain', 'Madrid', 'Universidad Francisco de Vitoria, CARRETERA MAJADAHONDA/M-515, 28223, Madrid',
 'https://www.cordonbleu.edu/madrid', 'rcointreau@cordonbleu.edu', '+34 917 15 10 46', 'Escuela de hostelería',
 1895, 300, 15, 4.6, 15000, 35000, 'EUR',
 '["Artes culinarias", "Gastronomía francesa", "Pastelería internacional"]'::jsonb,
 '["Prestigio internacional", "Certificación Le Cordon Bleu"]'::jsonb,
 '["Campus universitario", "Equipamiento profesional", "Red mundial"]'::jsonb,
 '["Español", "Inglés", "Francés"]'::jsonb,
 40.4398036, -3.8332748, true),

-- La Zarola
('La Zarola',
 'Escuela de cocina en Zaragoza especializada en experiencias gastronómicas para aficionados y profesionales.',
 'Spain', 'Zaragoza', 'C. de S. Miguel, 35, Casco Antiguo, 50001 Zaragoza',
 'http://www.lazarola.com/', 'info@lazarola.com', '+34 661 66 84 71', 'Escuela de cocina',
 2012, 60, 8, 4.7, 50, 180, 'EUR',
 '["Cocina tradicional", "Talleres temáticos", "Eventos gastronómicos"]'::jsonb,
 '["Experiencia certificada"]'::jsonb,
 '["Ubicación histórica", "Clases participativas", "Eventos privados"]'::jsonb,
 '["Español"]'::jsonb,
 41.6502304, -0.87823, true),

-- Club Mimo (diferente de Mimo Bite The Experience)
('Club Mimo',
 'Escuela de cocina en San Sebastián especializada en clases gastronómicas y experiencias culinarias.',
 'Spain', 'Donostia-San Sebastian', 'Okendo Kalea, 1, Sótano, 20004 Donostia-San Sebastian, Gipuzkoa',
 'http://club.mimo.eus/', 'info@clubmimo.eus', '+34 943 06 20 18', 'Escuela de cocina',
 2014, 35, 6, 4.9, 80, 200, 'EUR',
 '["Clases gastronómicas", "Experiencias culinarias", "Eventos privados"]'::jsonb,
 '["Certificación de experiencia"]'::jsonb,
 '["Instalaciones adaptadas", "Clases presenciales", "Ambiente acogedor"]'::jsonb,
 '["Español", "Euskera"]'::jsonb,
 43.3217859, -1.9804926, true),

-- Ama Ur Cooking Studio
('Ama Ur Cooking Studio',
 'Estudio de cocina especializado en experiencias gastronómicas personalizadas y clases privadas.',
 'Spain', 'San Sebastián', 'San Sebastián, Gipuzkoa',
 'http://www.amaurcook.com/', 'amaurcook@gmail.com', '+34 649 95 51 79', 'Escuela de cocina',
 2017, 20, 4, 5.0, 100, 300, 'EUR',
 '["Clases privadas", "Experiencias personalizadas", "Cocina creativa"]'::jsonb,
 '["Experiencia artesanal"]'::jsonb,
 '["Cita previa", "Grupos reducidos", "Ambiente familiar"]'::jsonb,
 '["Español", "Euskera"]'::jsonb,
 43.3078692, -1.9696011, true),

-- Cocina familiar con Javier Romero
('Cocina familiar con Javier Romero',
 'Escuela de cocina especializada en cocina casera y tradicional dirigida por el chef Javier Romero.',
 'Spain', 'Aldeanueva de Ebro', 'C. Martínez Moreno, 26559 Aldeanueva de Ebro, La Rioja',
 'http://www.cocina-familiar.com/', 'javier@cocina-familiar.com', '+34 605 16 66 45', 'Escuela de cocina',
 2013, 25, 5, 5.0, 60, 150, 'EUR',
 '["Cocina casera", "Recetas tradicionales", "Técnicas familiares"]'::jsonb,
 '["Chef certificado"]'::jsonb,
 '["Ambiente familiar", "Recetas auténticas", "Chef personal"]'::jsonb,
 '["Español"]'::jsonb,
 42.2292809, -1.8839159, true);