// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbeeuzqdvpsyzyovinyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiZWV1enFkdnBzeXp5b3ZpbnlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MzAyNDIsImV4cCI6MjA2ODQwNjI0Mn0.JKSUSSZZYkTFEwyvVmqeHafiEfu9RarTsKxkvjSmj4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});